# Base16 Gruvbox dark, hard 256 - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
colors:
  # Default colors
  primary:
    background: '#1d2021'
    foreground: '#d5c4a1'

  cursor:
    text: '#1d2021'
    cursor: '#d5c4a1'

  # Normal colors
  normal:
    black:   '#1d2021'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#d5c4a1'

  # Bright colors
  bright:
    black:   '#665c54'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#fbf1c7'

  indexed_colors:
    - { index: 16, color: '#fe8019' }
    - { index: 17, color: '#d65d0e' }
    - { index: 18, color: '#3c3836' }
    - { index: 19, color: '#504945' }
    - { index: 20, color: '#bdae93' }
    - { index: 21, color: '#ebdbb2' }
background_opacity: 1

# Font configuration
# Have to use size 6 when in i3
font:
    normal:
        family: Noto Sans Mono
    bold:
        family: Noto Sans Mono
        style: Bold
    italic:
        family: Noto Sans Mono
        style: Italic
    bold_italic:
        family: Noto Sans Mono
        style: Bold Italic
    size: 6.0
    # size: 11.0

# Cursor
cursor:
  style: Block
  unfocused_hollow: true

scrolling:
  history: 100000
  multiplier: 3

live_config_reload: true
