# Base16 Gruvbox dark, hard - alacritty color config
# Dawid Kurek (dawikur@gmail.com), morhetz (https://github.com/morhetz/gruvbox)
colors:
  # Default colors
  primary:
    background: '0x1d2021'
    foreground: '0xd5c4a1'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d2021'
    cursor: '0xd5c4a1'

  # Normal colors
  normal:
    black:   '0x1d2021'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xd5c4a1'

  # Bright colors
  bright:
    black:   '0x665c54'
    red:     '0xfe8019'
    green:   '0x3c3836'
    yellow:  '0x504945'
    blue:    '0xbdae93'
    magenta: '0xebdbb2'
    cyan:    '0xd65d0e'
    white:   '0xfbf1c7'

draw_bold_text_with_bright_colors: false

background_opacity: 1

# Font configuration
# Have to use size 6 when in i3
font:
    normal:
        family: Noto Sans Mono
    bold:
        family: Noto Sans Mono
        style: Bold
    italic:
        family: Noto Sans Mono
        style: Italic
    bold_italic:
        family: Noto Sans Mono
        style: Bold Italic
    size: 6.0
    # size: 11.0

# Cursor
cursor:
  style: Block
  unfocused_hollow: true

scrolling:
  history: 100000
  multiplier: 3

live_config_reload: true
