# Colors (Seoul256)
colors:
  # Default colors
  primary:
    background: '#1c1c1c'
    foreground: '#d0d0d0'

  # Normal colors
  normal:
    black:   '#4e4e4e'
    red:     '#d68787'
    green:   '#5f865f'
    yellow:  '#d8af5f'
    blue:    '#85add4'
    magenta: '#d7afaf'
    cyan:    '#87afaf'
    white:   '#d0d0d0'

  # Bright colors
  bright:
    black:   '#626262'
    red:     '#d75f87'
    green:   '#87af87'
    yellow:  '#ffd787'
    blue:    '#add4fb'
    magenta: '#ffafaf'
    cyan:    '#87d7d7'
    white:   '#e4e4e4'

background_opacity: 1

# Font configuration
font:
    normal:
        family: Noto Sans Mono
    bold:
        family: Noto Sans Mono
        style: Bold
    italic:
        family: Noto Sans Mono
        style: Italic
    bold_italic:
        family: Noto Sans Mono
        style: Bold Italic
    size: 10.0

# Cursor
cursor:
  style: Block
  unfocused_hollow: true

scrolling:
  history: 100000
  multiplier: 3

# key_bindings:
  # (Windows/Linux only)
  # - { key: V,        mods: Control|Shift, action: Paste            }
  # - { key: C,        mods: Control|Shift, action: Copy             }
  # - { key: Insert,   mods: Shift,         action: PasteSelection   }
  # - { key: Key0,     mods: Control,       action: ResetFontSize    }
  # - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  # - { key: Add,      mods: Control,       action: IncreaseFontSize }
  # - { key: Subtract, mods: Control,       action: DecreaseFontSize }
  # - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  # - { key: Return,   mods: Alt,           action: ToggleFullscreen }

live_config_reload: true

