# Colors (Gruvbox light)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#f9f5d7'
    # default background: '#fbf1c7'
    background: '#f9f5d7'
    # soft contrast: background = '#f2e5bc'
    foreground: '#3c3836'

  # Normal colors
  normal:
    black:   '#fbf1c7'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#7c6f64'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#427b58'
    white:   '#3c3836'

background_opacity: 1

# Font configuration
font:
    normal:
        family: Noto Sans Mono
    bold:
        family: Noto Sans Mono
        style: Bold
    italic:
        family: Noto Sans Mono
        style: Italic
    bold_italic:
        family: Noto Sans Mono
        style: Bold Italic
    size: 10.0

# Cursor
cursor:
  style: Block
  unfocused_hollow: true

scrolling:
  history: 100000
  multiplier: 3

# key_bindings:
  # (Windows/Linux only)
  # - { key: V,        mods: Control|Shift, action: Paste            }
  # - { key: C,        mods: Control|Shift, action: Copy             }
  # - { key: Insert,   mods: Shift,         action: PasteSelection   }
  # - { key: Key0,     mods: Control,       action: ResetFontSize    }
  # - { key: Equals,   mods: Control,       action: IncreaseFontSize }
  # - { key: Add,      mods: Control,       action: IncreaseFontSize }
  # - { key: Subtract, mods: Control,       action: DecreaseFontSize }
  # - { key: Minus,    mods: Control,       action: DecreaseFontSize }
  # - { key: Return,   mods: Alt,           action: ToggleFullscreen }

live_config_reload: true

