live_config_reload = true

[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x1d2021"
foreground = "0xdfbf8e"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 8.0

[font.bold]
family = "Noto Sans Mono"
style = "Bold"

[font.bold_italic]
family = "Noto Sans Mono"
style = "Bold Italic"

[font.italic]
family = "Noto Sans Mono"
style = "Italic"

[font.normal]
family = "Noto Sans Mono"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Shift|Control"

[scrolling]
history = 100000
multiplier = 3

[window]
opacity = 1.0
