# Colors (Gruvbox Material Dark Medium)
colors:
  primary:
    background: '0x1d2021'
    foreground: '0xdfbf8e'

  normal:
    black:   '0x665c54'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe78a4e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

  bright:
    black:   '0x928374'
    red:     '0xea6962'
    green:   '0xa9b665'
    yellow:  '0xe3a84e'
    blue:    '0x7daea3'
    magenta: '0xd3869b'
    cyan:    '0x89b482'
    white:   '0xdfbf8e'

window:
  opacity: 1.0

# Font configuration
font:
    normal:
        family: Noto Sans Mono
    bold:
        family: Noto Sans Mono
        style: Bold
    italic:
        family: Noto Sans Mono
        style: Italic
    bold_italic:
        family: Noto Sans Mono
        style: Bold Italic
    size: 6.0

# Cursor
cursor:
  style: Block
  unfocused_hollow: true

scrolling:
  history: 100000
  multiplier: 3

live_config_reload: true

key_bindings:
  # Vi Mode
  - { key: Space,  mods: Shift|Control,           action: ToggleViMode            }
  # - { key: Space,  mods: Shift|Control, mode: Vi, action: ScrollToBottom          }
  # - { key: Escape,                      mode: Vi, action: ClearSelection          }
  # - { key: I,                           mode: Vi, action: ScrollToBottom          }
  # - { key: I,                           mode: Vi, action: ToggleViMode            }
  # - { key: Y,      mods: Control,       mode: Vi, action: ScrollLineUp            }
  # - { key: E,      mods: Control,       mode: Vi, action: ScrollLineDown          }
  # - { key: G,                           mode: Vi, action: ScrollToTop             }
  # - { key: G,      mods: Shift,         mode: Vi, action: ScrollToBottom          }
  # - { key: B,      mods: Control,       mode: Vi, action: ScrollPageUp            }
  # - { key: F,      mods: Control,       mode: Vi, action: ScrollPageDown          }
  # - { key: U,      mods: Control,       mode: Vi, action: ScrollHalfPageUp        }
  # - { key: D,      mods: Control,       mode: Vi, action: ScrollHalfPageDown      }
  # - { key: Y,                           mode: Vi, action: Copy                    }
  # - { key: Y,                           mode: Vi, action: ClearSelection          }
  # - { key: Copy,                        mode: Vi, action: ClearSelection          }
  # - { key: V,                           mode: Vi, action: ToggleNormalSelection   }
  # - { key: V,      mods: Shift,         mode: Vi, action: ToggleLineSelection     }
  # - { key: V,      mods: Control,       mode: Vi, action: ToggleBlockSelection    }
  # - { key: V,      mods: Alt,           mode: Vi, action: ToggleSemanticSelection }
  # - { key: Return,                      mode: Vi, action: Open                    }
  # - { key: K,                           mode: Vi, action: Up                      }
  # - { key: J,                           mode: Vi, action: Down                    }
  # - { key: H,                           mode: Vi, action: Left                    }
  # - { key: L,                           mode: Vi, action: Right                   }
  # - { key: Up,                          mode: Vi, action: Up                      }
  # - { key: Down,                        mode: Vi, action: Down                    }
  # - { key: Left,                        mode: Vi, action: Left                    }
  # - { key: Right,                       mode: Vi, action: Right                   }
  # - { key: Key0,                        mode: Vi, action: First                   }
  # - { key: Key4,   mods: Shift,         mode: Vi, action: Last                    }
  # - { key: Key6,   mods: Shift,         mode: Vi, action: FirstOccupied           }
  # - { key: H,      mods: Shift,         mode: Vi, action: High                    }
  # - { key: M,      mods: Shift,         mode: Vi, action: Middle                  }
  # - { key: L,      mods: Shift,         mode: Vi, action: Low                     }
  # - { key: B,                           mode: Vi, action: SemanticLeft            }
  # - { key: W,                           mode: Vi, action: SemanticRight           }
  # - { key: E,                           mode: Vi, action: SemanticRightEnd        }
  # - { key: B,      mods: Shift,         mode: Vi, action: WordLeft                }
  # - { key: W,      mods: Shift,         mode: Vi, action: WordRight               }
  # - { key: E,      mods: Shift,         mode: Vi, action: WordRightEnd            }
  # - { key: Key5,   mods: Shift,         mode: Vi, action: Bracket                 }
  # - { key: Slash,                       mode: Vi, action: SearchForward           }
  # - { key: Slash,  mods: Shift,         mode: Vi, action: SearchBackward          }
  # - { key: N,                           mode: Vi, action: SearchNext              }
  # - { key: N,      mods: Shift,         mode: Vi, action: SearchPrevious          }
